// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBzxAu5dFF3sdiXFotY6KiTvSXckzpc1Ic',
    appId: '1:669633997898:web:1dd2020d6b0e1008618ab3',
    messagingSenderId: '669633997898',
    projectId: 'fruit-hub-4496a',
    authDomain: 'fruit-hub-4496a.firebaseapp.com',
    storageBucket: 'fruit-hub-4496a.firebasestorage.app',
    measurementId: 'G-G23YJ6SR2B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5gLqMk3hnNaFpPYkNmn13dUx73cz2iFk',
    appId: '1:669633997898:android:3c71a61ee438b038618ab3',
    messagingSenderId: '669633997898',
    projectId: 'fruit-hub-4496a',
    storageBucket: 'fruit-hub-4496a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAqTLoNlSu9atZpczfyhHvlvLdvCXlfckk',
    appId: '1:669633997898:ios:2559d38fbcd15753618ab3',
    messagingSenderId: '669633997898',
    projectId: 'fruit-hub-4496a',
    storageBucket: 'fruit-hub-4496a.firebasestorage.app',
    androidClientId: '669633997898-79u2lgd0tuq1grdsjv6ehh11ot5g5u8e.apps.googleusercontent.com',
    iosClientId: '669633997898-4o0uoqh6mss4l0cmdfecl2nkn5po0iba.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerceAppDashboard',
  );
}
